// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

import (
	"bytes"
	"fmt"
	"io"
	"model"
	"strconv"
	"time"
)

type Admin struct {
	// UID of the user
	UID string `json:"uid"`
	// Name of the user (if fetched)
	DisplayName *string `json:"displayName,omitempty"`
	// Email of the user
	Email *string `json:"email,omitempty"`
	// URL to the profile photo of the user (if fetched)
	PhotoURL *string `json:"photoURL,omitempty"`
	// Date when the user last logged in
	LastLoggedOn *time.Time `json:"lastLoggedOn,omitempty"`
	// Date when the user last interacted with the app
	LastActiveOn *time.Time `json:"lastActiveOn,omitempty"`
	// Date when the user account was created
	CreatedOn time.Time `json:"createdOn"`
}

type CollectionReorderData struct {
	// Team Collection being moved
	Collection *model.TeamCollection `json:"collection"`
	// Team Collection succeeding the collection being moved in its new position
	NextCollection *model.TeamCollection `json:"nextCollection,omitempty"`
}

type CreateInfraTokenResponse struct {
	// The infra token
	Token string `json:"token"`
	// Infra token info
	Info *model.InfraToken `json:"info"`
}

type CreateTeamRequestInput struct {
	// ID of the team the collection belongs to
	TeamID string `json:"teamID"`
	// JSON string representing the request data
	Request string `json:"request"`
	// Displayed title of the request
	Title string `json:"title"`
}

type EnableAndDisableSSOArgs struct {
	// Auth Provider
	Provider AuthProvider `json:"provider"`
	// Auth Provider Status
	Status ServiceStatus `json:"status"`
}

type Infra struct {
	// Admin who executed the action
	ExecutedBy *Admin `json:"executedBy"`
	// Returns a list of all admin users in infra
	Admins []*model.User `json:"admins"`
	// Returns a user info by UID
	UserInfo *model.User `json:"userInfo"`
	// Returns a list of all the users in infra
	AllUsers []*model.User `json:"allUsers"`
	// Returns a list of all the users in infra
	AllUsersV2 []*model.User `json:"allUsersV2"`
	// Returns a list of all the invited users
	InvitedUsers []*model.InvitedUser `json:"invitedUsers"`
	// Returns a list of all the teams in the infra
	AllTeams []*model.Team `json:"allTeams"`
	// Returns a team info by ID when requested by Admin
	TeamInfo *model.Team `json:"teamInfo"`
	// Return count of all the members in a team
	MembersCountInTeam int64 `json:"membersCountInTeam"`
	// Return count of all the stored collections in a team
	CollectionCountInTeam int64 `json:"collectionCountInTeam"`
	// Return count of all the stored requests in a team
	RequestCountInTeam int64 `json:"requestCountInTeam"`
	// Return count of all the stored environments in a team
	EnvironmentCountInTeam int64 `json:"environmentCountInTeam"`
	// Return all the pending invitations in a team
	PendingInvitationCountInTeam []*model.TeamInvitation `json:"pendingInvitationCountInTeam"`
	// Return total number of Users in organization
	UsersCount int64 `json:"usersCount"`
	// Return total number of Teams in organization
	TeamsCount int64 `json:"teamsCount"`
	// Return total number of Team Collections in organization
	TeamCollectionsCount int64 `json:"teamCollectionsCount"`
	// Return total number of Team Requests in organization
	TeamRequestsCount int64 `json:"teamRequestsCount"`
	// Returns a list of all the shortcodes in the infra
	AllShortcodes []*ShortcodeWithUserEmail `json:"allShortcodes"`
}

type InfraConfigArgs struct {
	// Infra Config Name
	Name InfraConfigEnum `json:"name"`
	// Infra Config Value
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}

type RequestReorderData struct {
	// Team Request being moved
	Request *model.TeamRequest `json:"request"`
	// Team Request succeeding the request being moved in its new position
	NextRequest *model.TeamRequest `json:"nextRequest,omitempty"`
}

type ShortcodeCreator struct {
	// Uid of user who created the shortcode
	UID string `json:"uid"`
	// Email of user who created the shortcode
	Email string `json:"email"`
}

type ShortcodeWithUserEmail struct {
	// The 12 digit alphanumeric code
	ID string `json:"id"`
	// JSON string representing the request data
	Request string `json:"request"`
	// JSON string representing the properties for an embed
	Properties *string `json:"properties,omitempty"`
	// Timestamp of when the Shortcode was created
	CreatedOn time.Time `json:"createdOn"`
	// Details of user who created the shortcode
	Creator *ShortcodeCreator `json:"creator,omitempty"`
}

type Subscription struct {
}

type UpdateTeamRequestInput struct {
	// JSON string representing the request data
	Request *string `json:"request,omitempty"`
	// Displayed title of the request
	Title *string `json:"title,omitempty"`
}

type UserCollectionDuplicatedData struct {
	// ID of the user collection
	ID string `json:"id"`
	// Displayed title of the user collection
	Title string `json:"title"`
	// JSON string representing the collection data
	Data *string `json:"data,omitempty"`
	// Type of the user collection
	Type model.ReqType `json:"type"`
	// Parent ID of the duplicated User Collection
	ParentID *string `json:"parentID,omitempty"`
	// User ID of the duplicated User Collection
	UserID string `json:"userID"`
	// Child collections of the duplicated User Collection
	ChildCollections string `json:"childCollections"`
	// Requests of the duplicated User Collection
	Requests []*model.UserRequest `json:"requests"`
}

type UserCollectionExportJSONData struct {
	// Stringified contents of the collection
	ExportedCollection string `json:"exportedCollection"`
	// Type of the user collection
	CollectionType model.ReqType `json:"collectionType"`
}

type UserCollectionRemovedData struct {
	// ID of User Collection being removed
	ID string `json:"id"`
	// Type of the user collection
	Type model.ReqType `json:"type"`
}

type UserCollectionReorderData struct {
	// User Collection being moved
	UserCollection *model.UserCollection `json:"userCollection"`
	// User Collection succeeding the collection being moved in its new position
	NextUserCollection *model.UserCollection `json:"nextUserCollection,omitempty"`
}

type UserCollectionSortData struct {
	// ID of the parent collection
	ParentCollectionID *string `json:"parentCollectionID,omitempty"`
	// Sorting option
	SortOption SortOptions `json:"sortOption"`
}

type UserDeletionResult struct {
	// UID of the user
	UserUID string `json:"userUID"`
	// Flag to determine if user deletion was successful or not
	IsDeleted bool `json:"isDeleted"`
	// Error message if user deletion was not successful
	ErrorMessage *string `json:"errorMessage,omitempty"`
}

type UserHistoryDeletedManyData struct {
	// Number of user histories deleted
	Count int `json:"count"`
	// Type of the request in the history
	ReqType model.ReqType `json:"reqType"`
}

type UserRequestReorderData struct {
	// User request being moved
	Request *model.UserRequest `json:"request"`
	// User request succeeding the request being moved in its new position
	NextRequest *model.UserRequest `json:"nextRequest,omitempty"`
}

type AuthProvider string

const (
	AuthProviderGoogle    AuthProvider = "GOOGLE"
	AuthProviderGithub    AuthProvider = "GITHUB"
	AuthProviderMicrosoft AuthProvider = "MICROSOFT"
	AuthProviderEmail     AuthProvider = "EMAIL"
)

var AllAuthProvider = []AuthProvider{
	AuthProviderGoogle,
	AuthProviderGithub,
	AuthProviderMicrosoft,
	AuthProviderEmail,
}

func (e AuthProvider) IsValid() bool {
	switch e {
	case AuthProviderGoogle, AuthProviderGithub, AuthProviderMicrosoft, AuthProviderEmail:
		return true
	}
	return false
}

func (e AuthProvider) String() string {
	return string(e)
}

func (e *AuthProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthProvider", str)
	}
	return nil
}

func (e AuthProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InfraConfigEnum string

const (
	InfraConfigEnumOnboardingCompleted         InfraConfigEnum = "ONBOARDING_COMPLETED"
	InfraConfigEnumOnboardingRecoveryToken     InfraConfigEnum = "ONBOARDING_RECOVERY_TOKEN"
	InfraConfigEnumJwtSecret                   InfraConfigEnum = "JWT_SECRET"
	InfraConfigEnumSessionSecret               InfraConfigEnum = "SESSION_SECRET"
	InfraConfigEnumTokenSaltComplexity         InfraConfigEnum = "TOKEN_SALT_COMPLEXITY"
	InfraConfigEnumMagicLinkTokenValidity      InfraConfigEnum = "MAGIC_LINK_TOKEN_VALIDITY"
	InfraConfigEnumRefreshTokenValidity        InfraConfigEnum = "REFRESH_TOKEN_VALIDITY"
	InfraConfigEnumAccessTokenValidity         InfraConfigEnum = "ACCESS_TOKEN_VALIDITY"
	InfraConfigEnumAllowSecureCookies          InfraConfigEnum = "ALLOW_SECURE_COOKIES"
	InfraConfigEnumRateLimitTTL                InfraConfigEnum = "RATE_LIMIT_TTL"
	InfraConfigEnumRateLimitMax                InfraConfigEnum = "RATE_LIMIT_MAX"
	InfraConfigEnumMailerSMTPEnable            InfraConfigEnum = "MAILER_SMTP_ENABLE"
	InfraConfigEnumMailerUseCustomConfigs      InfraConfigEnum = "MAILER_USE_CUSTOM_CONFIGS"
	InfraConfigEnumMailerSMTPURL               InfraConfigEnum = "MAILER_SMTP_URL"
	InfraConfigEnumMailerAddressFrom           InfraConfigEnum = "MAILER_ADDRESS_FROM"
	InfraConfigEnumMailerSMTPHost              InfraConfigEnum = "MAILER_SMTP_HOST"
	InfraConfigEnumMailerSMTPPort              InfraConfigEnum = "MAILER_SMTP_PORT"
	InfraConfigEnumMailerSMTPSecure            InfraConfigEnum = "MAILER_SMTP_SECURE"
	InfraConfigEnumMailerSMTPUser              InfraConfigEnum = "MAILER_SMTP_USER"
	InfraConfigEnumMailerSMTPPassword          InfraConfigEnum = "MAILER_SMTP_PASSWORD"
	InfraConfigEnumMailerTLSRejectUnauthorized InfraConfigEnum = "MAILER_TLS_REJECT_UNAUTHORIZED"
	InfraConfigEnumGoogleClientID              InfraConfigEnum = "GOOGLE_CLIENT_ID"
	InfraConfigEnumGoogleClientSecret          InfraConfigEnum = "GOOGLE_CLIENT_SECRET"
	InfraConfigEnumGoogleCallbackURL           InfraConfigEnum = "GOOGLE_CALLBACK_URL"
	InfraConfigEnumGoogleScope                 InfraConfigEnum = "GOOGLE_SCOPE"
	InfraConfigEnumGithubClientID              InfraConfigEnum = "GITHUB_CLIENT_ID"
	InfraConfigEnumGithubClientSecret          InfraConfigEnum = "GITHUB_CLIENT_SECRET"
	InfraConfigEnumGithubCallbackURL           InfraConfigEnum = "GITHUB_CALLBACK_URL"
	InfraConfigEnumGithubScope                 InfraConfigEnum = "GITHUB_SCOPE"
	InfraConfigEnumMicrosoftClientID           InfraConfigEnum = "MICROSOFT_CLIENT_ID"
	InfraConfigEnumMicrosoftClientSecret       InfraConfigEnum = "MICROSOFT_CLIENT_SECRET"
	InfraConfigEnumMicrosoftCallbackURL        InfraConfigEnum = "MICROSOFT_CALLBACK_URL"
	InfraConfigEnumMicrosoftScope              InfraConfigEnum = "MICROSOFT_SCOPE"
	InfraConfigEnumMicrosoftTenant             InfraConfigEnum = "MICROSOFT_TENANT"
	InfraConfigEnumViteAllowedAuthProviders    InfraConfigEnum = "VITE_ALLOWED_AUTH_PROVIDERS"
	InfraConfigEnumAllowAnalyticsCollection    InfraConfigEnum = "ALLOW_ANALYTICS_COLLECTION"
	InfraConfigEnumAnalyticsUserID             InfraConfigEnum = "ANALYTICS_USER_ID"
	InfraConfigEnumIsFirstTimeInfraSetup       InfraConfigEnum = "IS_FIRST_TIME_INFRA_SETUP"
	InfraConfigEnumUserHistoryStoreEnabled     InfraConfigEnum = "USER_HISTORY_STORE_ENABLED"
)

var AllInfraConfigEnum = []InfraConfigEnum{
	InfraConfigEnumOnboardingCompleted,
	InfraConfigEnumOnboardingRecoveryToken,
	InfraConfigEnumJwtSecret,
	InfraConfigEnumSessionSecret,
	InfraConfigEnumTokenSaltComplexity,
	InfraConfigEnumMagicLinkTokenValidity,
	InfraConfigEnumRefreshTokenValidity,
	InfraConfigEnumAccessTokenValidity,
	InfraConfigEnumAllowSecureCookies,
	InfraConfigEnumRateLimitTTL,
	InfraConfigEnumRateLimitMax,
	InfraConfigEnumMailerSMTPEnable,
	InfraConfigEnumMailerUseCustomConfigs,
	InfraConfigEnumMailerSMTPURL,
	InfraConfigEnumMailerAddressFrom,
	InfraConfigEnumMailerSMTPHost,
	InfraConfigEnumMailerSMTPPort,
	InfraConfigEnumMailerSMTPSecure,
	InfraConfigEnumMailerSMTPUser,
	InfraConfigEnumMailerSMTPPassword,
	InfraConfigEnumMailerTLSRejectUnauthorized,
	InfraConfigEnumGoogleClientID,
	InfraConfigEnumGoogleClientSecret,
	InfraConfigEnumGoogleCallbackURL,
	InfraConfigEnumGoogleScope,
	InfraConfigEnumGithubClientID,
	InfraConfigEnumGithubClientSecret,
	InfraConfigEnumGithubCallbackURL,
	InfraConfigEnumGithubScope,
	InfraConfigEnumMicrosoftClientID,
	InfraConfigEnumMicrosoftClientSecret,
	InfraConfigEnumMicrosoftCallbackURL,
	InfraConfigEnumMicrosoftScope,
	InfraConfigEnumMicrosoftTenant,
	InfraConfigEnumViteAllowedAuthProviders,
	InfraConfigEnumAllowAnalyticsCollection,
	InfraConfigEnumAnalyticsUserID,
	InfraConfigEnumIsFirstTimeInfraSetup,
	InfraConfigEnumUserHistoryStoreEnabled,
}

func (e InfraConfigEnum) IsValid() bool {
	switch e {
	case InfraConfigEnumOnboardingCompleted, InfraConfigEnumOnboardingRecoveryToken, InfraConfigEnumJwtSecret, InfraConfigEnumSessionSecret, InfraConfigEnumTokenSaltComplexity, InfraConfigEnumMagicLinkTokenValidity, InfraConfigEnumRefreshTokenValidity, InfraConfigEnumAccessTokenValidity, InfraConfigEnumAllowSecureCookies, InfraConfigEnumRateLimitTTL, InfraConfigEnumRateLimitMax, InfraConfigEnumMailerSMTPEnable, InfraConfigEnumMailerUseCustomConfigs, InfraConfigEnumMailerSMTPURL, InfraConfigEnumMailerAddressFrom, InfraConfigEnumMailerSMTPHost, InfraConfigEnumMailerSMTPPort, InfraConfigEnumMailerSMTPSecure, InfraConfigEnumMailerSMTPUser, InfraConfigEnumMailerSMTPPassword, InfraConfigEnumMailerTLSRejectUnauthorized, InfraConfigEnumGoogleClientID, InfraConfigEnumGoogleClientSecret, InfraConfigEnumGoogleCallbackURL, InfraConfigEnumGoogleScope, InfraConfigEnumGithubClientID, InfraConfigEnumGithubClientSecret, InfraConfigEnumGithubCallbackURL, InfraConfigEnumGithubScope, InfraConfigEnumMicrosoftClientID, InfraConfigEnumMicrosoftClientSecret, InfraConfigEnumMicrosoftCallbackURL, InfraConfigEnumMicrosoftScope, InfraConfigEnumMicrosoftTenant, InfraConfigEnumViteAllowedAuthProviders, InfraConfigEnumAllowAnalyticsCollection, InfraConfigEnumAnalyticsUserID, InfraConfigEnumIsFirstTimeInfraSetup, InfraConfigEnumUserHistoryStoreEnabled:
		return true
	}
	return false
}

func (e InfraConfigEnum) String() string {
	return string(e)
}

func (e *InfraConfigEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InfraConfigEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InfraConfigEnum", str)
	}
	return nil
}

func (e InfraConfigEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InfraConfigEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InfraConfigEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceStatus string

const (
	ServiceStatusEnable  ServiceStatus = "ENABLE"
	ServiceStatusDisable ServiceStatus = "DISABLE"
)

var AllServiceStatus = []ServiceStatus{
	ServiceStatusEnable,
	ServiceStatusDisable,
}

func (e ServiceStatus) IsValid() bool {
	switch e {
	case ServiceStatusEnable, ServiceStatusDisable:
		return true
	}
	return false
}

func (e ServiceStatus) String() string {
	return string(e)
}

func (e *ServiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceStatus", str)
	}
	return nil
}

func (e ServiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOptions string

const (
	SortOptionsTitleAsc  SortOptions = "TITLE_ASC"
	SortOptionsTitleDesc SortOptions = "TITLE_DESC"
)

var AllSortOptions = []SortOptions{
	SortOptionsTitleAsc,
	SortOptionsTitleDesc,
}

func (e SortOptions) IsValid() bool {
	switch e {
	case SortOptionsTitleAsc, SortOptionsTitleDesc:
		return true
	}
	return false
}

func (e SortOptions) String() string {
	return string(e)
}

func (e *SortOptions) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOptions(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOptions", str)
	}
	return nil
}

func (e SortOptions) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOptions) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOptions) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
