// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"model"
)

func newInfraToken(db *gorm.DB, opts ...gen.DOOption) infraToken {
	_infraToken := infraToken{}

	_infraToken.infraTokenDo.UseDB(db, opts...)
	_infraToken.infraTokenDo.UseModel(&model.InfraToken{})

	tableName := _infraToken.infraTokenDo.TableName()
	_infraToken.ALL = field.NewAsterisk(tableName)
	_infraToken.ID = field.NewString(tableName, "id")
	_infraToken.CreatorUID = field.NewString(tableName, "creatorUid")
	_infraToken.Label = field.NewString(tableName, "label")
	_infraToken.Token = field.NewString(tableName, "token")
	_infraToken.ExpiresOn = field.NewTime(tableName, "expiresOn")
	_infraToken.CreatedOn = field.NewTime(tableName, "createdOn")
	_infraToken.UpdatedOn = field.NewTime(tableName, "updatedOn")

	_infraToken.fillFieldMap()

	return _infraToken
}

type infraToken struct {
	infraTokenDo

	ALL        field.Asterisk
	ID         field.String
	CreatorUID field.String
	Label      field.String
	Token      field.String
	ExpiresOn  field.Time
	CreatedOn  field.Time
	UpdatedOn  field.Time

	fieldMap map[string]field.Expr
}

func (i infraToken) Table(newTableName string) *infraToken {
	i.infraTokenDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i infraToken) As(alias string) *infraToken {
	i.infraTokenDo.DO = *(i.infraTokenDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *infraToken) updateTableName(table string) *infraToken {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.CreatorUID = field.NewString(table, "creatorUid")
	i.Label = field.NewString(table, "label")
	i.Token = field.NewString(table, "token")
	i.ExpiresOn = field.NewTime(table, "expiresOn")
	i.CreatedOn = field.NewTime(table, "createdOn")
	i.UpdatedOn = field.NewTime(table, "updatedOn")

	i.fillFieldMap()

	return i
}

func (i *infraToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *infraToken) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 7)
	i.fieldMap["id"] = i.ID
	i.fieldMap["creatorUid"] = i.CreatorUID
	i.fieldMap["label"] = i.Label
	i.fieldMap["token"] = i.Token
	i.fieldMap["expiresOn"] = i.ExpiresOn
	i.fieldMap["createdOn"] = i.CreatedOn
	i.fieldMap["updatedOn"] = i.UpdatedOn
}

func (i infraToken) clone(db *gorm.DB) infraToken {
	i.infraTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i infraToken) replaceDB(db *gorm.DB) infraToken {
	i.infraTokenDo.ReplaceDB(db)
	return i
}

type infraTokenDo struct{ gen.DO }

type IInfraTokenDo interface {
	gen.SubQuery
	Debug() IInfraTokenDo
	WithContext(ctx context.Context) IInfraTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInfraTokenDo
	WriteDB() IInfraTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInfraTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInfraTokenDo
	Not(conds ...gen.Condition) IInfraTokenDo
	Or(conds ...gen.Condition) IInfraTokenDo
	Select(conds ...field.Expr) IInfraTokenDo
	Where(conds ...gen.Condition) IInfraTokenDo
	Order(conds ...field.Expr) IInfraTokenDo
	Distinct(cols ...field.Expr) IInfraTokenDo
	Omit(cols ...field.Expr) IInfraTokenDo
	Join(table schema.Tabler, on ...field.Expr) IInfraTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInfraTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInfraTokenDo
	Group(cols ...field.Expr) IInfraTokenDo
	Having(conds ...gen.Condition) IInfraTokenDo
	Limit(limit int) IInfraTokenDo
	Offset(offset int) IInfraTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraTokenDo
	Unscoped() IInfraTokenDo
	Create(values ...*model.InfraToken) error
	CreateInBatches(values []*model.InfraToken, batchSize int) error
	Save(values ...*model.InfraToken) error
	First() (*model.InfraToken, error)
	Take() (*model.InfraToken, error)
	Last() (*model.InfraToken, error)
	Find() ([]*model.InfraToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraToken, err error)
	FindInBatches(result *[]*model.InfraToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InfraToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInfraTokenDo
	Assign(attrs ...field.AssignExpr) IInfraTokenDo
	Joins(fields ...field.RelationField) IInfraTokenDo
	Preload(fields ...field.RelationField) IInfraTokenDo
	FirstOrInit() (*model.InfraToken, error)
	FirstOrCreate() (*model.InfraToken, error)
	FindByPage(offset int, limit int) (result []*model.InfraToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInfraTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i infraTokenDo) Debug() IInfraTokenDo {
	return i.withDO(i.DO.Debug())
}

func (i infraTokenDo) WithContext(ctx context.Context) IInfraTokenDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i infraTokenDo) ReadDB() IInfraTokenDo {
	return i.Clauses(dbresolver.Read)
}

func (i infraTokenDo) WriteDB() IInfraTokenDo {
	return i.Clauses(dbresolver.Write)
}

func (i infraTokenDo) Session(config *gorm.Session) IInfraTokenDo {
	return i.withDO(i.DO.Session(config))
}

func (i infraTokenDo) Clauses(conds ...clause.Expression) IInfraTokenDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i infraTokenDo) Returning(value interface{}, columns ...string) IInfraTokenDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i infraTokenDo) Not(conds ...gen.Condition) IInfraTokenDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i infraTokenDo) Or(conds ...gen.Condition) IInfraTokenDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i infraTokenDo) Select(conds ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i infraTokenDo) Where(conds ...gen.Condition) IInfraTokenDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i infraTokenDo) Order(conds ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i infraTokenDo) Distinct(cols ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i infraTokenDo) Omit(cols ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i infraTokenDo) Join(table schema.Tabler, on ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i infraTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i infraTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i infraTokenDo) Group(cols ...field.Expr) IInfraTokenDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i infraTokenDo) Having(conds ...gen.Condition) IInfraTokenDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i infraTokenDo) Limit(limit int) IInfraTokenDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i infraTokenDo) Offset(offset int) IInfraTokenDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i infraTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInfraTokenDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i infraTokenDo) Unscoped() IInfraTokenDo {
	return i.withDO(i.DO.Unscoped())
}

func (i infraTokenDo) Create(values ...*model.InfraToken) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i infraTokenDo) CreateInBatches(values []*model.InfraToken, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i infraTokenDo) Save(values ...*model.InfraToken) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i infraTokenDo) First() (*model.InfraToken, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraToken), nil
	}
}

func (i infraTokenDo) Take() (*model.InfraToken, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraToken), nil
	}
}

func (i infraTokenDo) Last() (*model.InfraToken, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraToken), nil
	}
}

func (i infraTokenDo) Find() ([]*model.InfraToken, error) {
	result, err := i.DO.Find()
	return result.([]*model.InfraToken), err
}

func (i infraTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InfraToken, err error) {
	buf := make([]*model.InfraToken, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i infraTokenDo) FindInBatches(result *[]*model.InfraToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i infraTokenDo) Attrs(attrs ...field.AssignExpr) IInfraTokenDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i infraTokenDo) Assign(attrs ...field.AssignExpr) IInfraTokenDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i infraTokenDo) Joins(fields ...field.RelationField) IInfraTokenDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i infraTokenDo) Preload(fields ...field.RelationField) IInfraTokenDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i infraTokenDo) FirstOrInit() (*model.InfraToken, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraToken), nil
	}
}

func (i infraTokenDo) FirstOrCreate() (*model.InfraToken, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InfraToken), nil
	}
}

func (i infraTokenDo) FindByPage(offset int, limit int) (result []*model.InfraToken, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i infraTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i infraTokenDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i infraTokenDo) Delete(models ...*model.InfraToken) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *infraTokenDo) withDO(do gen.Dao) *infraTokenDo {
	i.DO = *do.(*gen.DO)
	return i
}
