// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"
	"testing"

	"model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.PersonalAccessToken{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.PersonalAccessToken{}) fail: %s", err)
	}
}

func Test_personalAccessTokenQuery(t *testing.T) {
	personalAccessToken := newPersonalAccessToken(_gen_test_db)
	personalAccessToken = *personalAccessToken.As(personalAccessToken.TableName())
	_do := personalAccessToken.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(personalAccessToken.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <PersonalAccessToken> fail:", err)
		return
	}

	_, ok := personalAccessToken.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from personalAccessToken success")
	}

	err = _do.Create(&model.PersonalAccessToken{})
	if err != nil {
		t.Error("create item in table <PersonalAccessToken> fail:", err)
	}

	err = _do.Save(&model.PersonalAccessToken{})
	if err != nil {
		t.Error("create item in table <PersonalAccessToken> fail:", err)
	}

	err = _do.CreateInBatches([]*model.PersonalAccessToken{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Select(personalAccessToken.ALL).Take()
	if err != nil {
		t.Error("Take() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <PersonalAccessToken> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.PersonalAccessToken{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Select(personalAccessToken.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Select(personalAccessToken.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <PersonalAccessToken> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.ScanByPage(&model.PersonalAccessToken{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <PersonalAccessToken> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <PersonalAccessToken> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <PersonalAccessToken> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <PersonalAccessToken> fail:", err)
	}
}
