// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"
	"testing"

	"model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.TeamEnvironment{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.TeamEnvironment{}) fail: %s", err)
	}
}

func Test_teamEnvironmentQuery(t *testing.T) {
	teamEnvironment := newTeamEnvironment(db)
	teamEnvironment = *teamEnvironment.As(teamEnvironment.TableName())
	_do := teamEnvironment.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(teamEnvironment.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <TeamEnvironment> fail:", err)
		return
	}

	_, ok := teamEnvironment.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from teamEnvironment success")
	}

	err = _do.Create(&model.TeamEnvironment{})
	if err != nil {
		t.Error("create item in table <TeamEnvironment> fail:", err)
	}

	err = _do.Save(&model.TeamEnvironment{})
	if err != nil {
		t.Error("create item in table <TeamEnvironment> fail:", err)
	}

	err = _do.CreateInBatches([]*model.TeamEnvironment{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Select(teamEnvironment.ALL).Take()
	if err != nil {
		t.Error("Take() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <TeamEnvironment> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.TeamEnvironment{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Select(teamEnvironment.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Select(teamEnvironment.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <TeamEnvironment> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.ScanByPage(&model.TeamEnvironment{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <TeamEnvironment> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <TeamEnvironment> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <TeamEnvironment> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <TeamEnvironment> fail:", err)
	}
}
