// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"
	"testing"

	"model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.Team{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Team{}) fail: %s", err)
	}
}

func Test_teamQuery(t *testing.T) {
	team := newTeam(db)
	team = *team.As(team.TableName())
	_do := team.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(team.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <Team> fail:", err)
		return
	}

	_, ok := team.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from team success")
	}

	err = _do.Create(&model.Team{})
	if err != nil {
		t.Error("create item in table <Team> fail:", err)
	}

	err = _do.Save(&model.Team{})
	if err != nil {
		t.Error("create item in table <Team> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Team{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <Team> fail:", err)
	}

	_, err = _do.Select(team.ALL).Take()
	if err != nil {
		t.Error("Take() on table <Team> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <Team> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <Team> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <Team> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Team{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <Team> fail:", err)
	}

	_, err = _do.Select(team.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <Team> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <Team> fail:", err)
	}

	_, err = _do.Select(team.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <Team> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <Team> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <Team> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <Team> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Team{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <Team> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <Team> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <Team> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <Team> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <Team> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <Team> fail:", err)
	}
}
