// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInfraToken = "InfraToken"

// InfraToken mapped from table <InfraToken>
type InfraToken struct {
	ID         string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	CreatorUID string     `gorm:"column:creatorUid;type:text;not null" json:"creatorUid"`
	Label      string     `gorm:"column:label;type:text;not null" json:"label"`
	Token      string     `gorm:"column:token;type:text;not null;uniqueIndex:InfraToken_token_key,priority:1" json:"token"`
	ExpiresOn  *time.Time `gorm:"column:expiresOn;type:timestamp(3) with time zone" json:"expiresOn"`
	CreatedOn  time.Time  `gorm:"column:createdOn;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP" json:"createdOn"`
	UpdatedOn  time.Time  `gorm:"column:updatedOn;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP;autoUpdateTime" json:"updatedOn"`
}

// TableName InfraToken's table name
func (*InfraToken) TableName() string {
	return TableNameInfraToken
}
