// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePersonalAccessToken = "PersonalAccessToken"

// PersonalAccessToken mapped from table <PersonalAccessToken>
type PersonalAccessToken struct {
	ID        string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	UserUID   string     `gorm:"column:userUid;type:text;not null" json:"userUid"`
	Label     string     `gorm:"column:label;type:text;not null" json:"label"`
	Token     string     `gorm:"column:token;type:text;not null;uniqueIndex:PersonalAccessToken_token_key,priority:1" json:"token"`
	ExpiresOn *time.Time `gorm:"column:expiresOn;type:timestamp(3) with time zone" json:"expiresOn"`
	CreatedOn time.Time  `gorm:"column:createdOn;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP" json:"createdOn"`
	UpdatedOn time.Time  `gorm:"column:updatedOn;type:timestamp(3) with time zone;not null;autoUpdateTime" json:"updatedOn"`
}

// TableName PersonalAccessToken's table name
func (*PersonalAccessToken) TableName() string {
	return TableNamePersonalAccessToken
}
