// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShortcode = "Shortcode"

// Shortcode mapped from table <Shortcode>
type Shortcode struct {
	ID              string    `gorm:"column:id;type:text;primaryKey;uniqueIndex:Shortcode_id_key,priority:1;uniqueIndex:Shortcode_id_creatorUid_key,priority:2" json:"id"`
	Request         string    `gorm:"column:request;type:jsonb;not null" json:"request"`
	CreatorUID      *string   `gorm:"column:creatorUid;type:text;uniqueIndex:Shortcode_id_creatorUid_key,priority:1" json:"creatorUid"`
	CreatedOn       time.Time `gorm:"column:createdOn;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP" json:"createdOn"`
	EmbedProperties *string   `gorm:"column:embedProperties;type:jsonb" json:"embedProperties"`
	UpdatedOn       time.Time `gorm:"column:updatedOn;type:timestamp(3) with time zone;not null;default:CURRENT_TIMESTAMP;autoUpdateTime" json:"updatedOn"`
	Creator         *User     `gorm:"foreignKey:CreatorUID;references:UID" json:"creator"`
}

// TableName Shortcode's table name
func (*Shortcode) TableName() string {
	return TableNameShortcode
}

func (s *Shortcode) IsOwner(uid string) bool {
	if s.CreatorUID == nil {
		return false
	}
	return *s.CreatorUID == uid
}
