// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserHistory = "UserHistory"

// UserHistory mapped from table <UserHistory>
type UserHistory struct {
	ID               string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	UserUID          string     `gorm:"column:userUid;type:text;not null" json:"userUid"`
	ReqType          ReqType    `gorm:"column:reqType;type:req_type;not null" json:"reqType"`
	Request          string      `gorm:"column:request;type:jsonb;not null" json:"request"`
	ResponseMetadata string      `gorm:"column:responseMetadata;type:jsonb;not null" json:"responseMetadata"`
	IsStarred        bool       `gorm:"column:isStarred;type:boolean;not null" json:"isStarred"`
	ExecutedOn       time.Time  `gorm:"column:executedOn;type:timestamp(3) without time zone;not null;default:CURRENT_TIMESTAMP" json:"executedOn"`
	User	  		 User 	   	`gorm:"foreignKey:UserUID" json:"user"`
}

// TableName UserHistory's table name
func (*UserHistory) TableName() string {
	return TableNameUserHistory
}

func (h *UserHistory) IsOwner(uid string) bool {
	return h.UserUID == uid
}
