// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserEnvironment = "UserEnvironment"

// UserEnvironment mapped from table <UserEnvironment>
type UserEnvironment struct {
	ID        string  `gorm:"column:id;type:text;primaryKey" json:"id"`
	UserUID   string  `gorm:"column:userUid;type:text;not null" json:"userUid"`
	Name      *string `gorm:"column:name;type:text" json:"name"`
	Variables string   `gorm:"column:variables;type:jsonb;not null" json:"variables"`
	IsGlobal  bool    `gorm:"column:isGlobal;type:boolean;not null" json:"isGlobal"`
	User	  User 	  `gorm:"foreignKey:UserUID" json:"user"`
}

// TableName UserEnvironment's table name
func (*UserEnvironment) TableName() string {
	return TableNameUserEnvironment
}

func (e *UserEnvironment) IsOwner(uid string) bool {
	return e.UserUID == uid
}
